### ISSUE TITLE
Zbyt krótki czas wyświetlenia komunikatu o braku możliwości rejestracji

### ISSUE THREAD

**Issue by danutaj23** [pdyba/aioquiz#170]
![komunikat](https://user-images.githubusercontent.com/22411234/33243933-dc107b74-d2ee-11e7-8e90-3156ff887624.png)
Stan początkowy.

![komunikat1](https://user-images.githubusercontent.com/22411234/33243849-a971b094-d2ed-11e7-9aa8-782ef48441db.png)
Wyświetlenie komunikatu po kliknięciu w `Register`. Komunikat pojawia się na mniej niż sekundę.

![komunikat2](https://user-images.githubusercontent.com/22411234/33243895-38cbb046-d2ee-11e7-887b-7af18d1eeb41.png)
Stan końcowy.

**Comment by pdyba** [comment]
Tam trzeba będzie odwrócić logikę :) żeby uniknąć konfuzji - aktualnie rejestracja jest aktywna.
ale to jest feature nie bug.
