### ISSUE TITLE
Nie można zmienić hasła i usunąć konta

### ISSUE THREAD

**Issue by danutaj23** [pdyba/aioquiz#189]
Po kliknięciu w `Change Password` i ` Delete account` otrzymuję komunikat:
![success](https://user-images.githubusercontent.com/22411234/34748713-23622c76-f59e-11e7-802d-1644cf141493.png)

**Comment by danutaj23** [comment]
Czy prace zostały zakończone? 
Można wprowadzić hasło krótsze niż 8 znaków. Można też pozostawić puste pole. Na puste hasło nie da się zalogować, ale na szczęście działa magiczny link :-)
A przy okazji - nagłówek maila z magicznym zawiera `pyladiesstart.pl`

**Comment by pdyba** [comment]
1wsza część jest juz poprawiona ;) czasmi potrzebny jest ctrl+shift+r zeby storna sie poprawnie odswiezyla (czasami nawet z wlaczonym inspektorem) :)

**Comment by pdyba** [comment]
A przy okazji - nagłówek maila z magicznym zawiera pyladiesstart.pl - możesz mi to pokazać jutro przed/po zajęciach ?

**Comment by pdyba** [comment]
https://github.com/pdyba/aioquiz/pull/195
Fix na validacje hasła w backendzie ;)

**Comment by danutaj23** [comment]
Coś chyba użarłam pisząc o nagłówku maila. Nagłówek wygląda tak: 

> Received:
> from static.99.29.243.136.clients.your-server.de ([136.243.29.99]:56030 helo=**pyladiesstart.pl**) by az0094.srv.az.pl with esmtpsa (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256) (Exim 4.87) (envelope-from <app@pylove.org>) id 1ebMfZ-0007or-3C for moj@email.pl'

Idę dziś na wagary :-]
