### ISSUE TITLE
Nie można odzyskać hasła

### ISSUE THREAD

**Issue by danutaj23** [pdyba/aioquiz#199]
Po podaniu prawidłowego e-maila i kliknięciu `OK`, otrzymuję komunikat `Error sending e-mail`.

Czy dobrze rozumiem, że to działa tak, że nowe hasło jest już wygenerowane, tylko maila nie dostałam, a wszelkie próby logowania na stare hasło zakończą się niepowodzeniem?

**Comment by pdyba** [comment]
naprawione
