### ISSUE TITLE
Można korzystać ze strony bez akceptacji Polityki Prywatności

### ISSUE THREAD

**Issue by danutaj23** [pdyba/aioquiz#246]
W wyświetlonym po zalogowaniu komunikacie, użytkownik może kliknąć prawym przyciskiem myszy w link kryjący się pod testem "Poliykę Prywatności" (literówka!) i otworzyć stronę w nowej karcie, następnie zamyka stronę, na której dokonał logowania i korzysta z tej nowo otwartej. Nie zostaje wylogowany.

![polityka prywatnosci](https://user-images.githubusercontent.com/22411234/40081115-579e3528-588d-11e8-9ab4-37ad6afb0bda.png)

**Comment by pdyba** [comment]
nice catch!
